In [6]:
!python -m pip install numpy

^C


In [43]:
import numpy as np
b=np.array([[5,7,8],[7,3,4]])
b

array([[5, 7, 8],
       [7, 3, 4]])

In [58]:
b[1,0]=10
b[1,1]=15
b[1,2]=12
b[:,1]=30,46
b[1,:]=10,20,30
b
print(b+3)
np.append(b,[[1,1,1]],axis=0)                       #axis 0=row; 1=column                      

[[ 8 33 11]
 [13 23 33]]


array([[ 5, 30,  8],
       [10, 20, 30],
       [ 1,  1,  1]])

In [63]:
np.append(b,[[1],[1]],axis=1) 

array([[ 5, 30,  8,  1],
       [10, 20, 30,  1]])

In [64]:
np.delete(b,1,axis=1)

array([[ 5,  8],
       [10, 30]])

In [23]:
k=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k.shape
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [35]:
m=np.array([[[4,8],[3,1],[6,9]],
            [[41,81],[31,11],[61,91]],
            [[7,71],[5,51],[13,151]]])
print(m)
m.shape

[[[  4   8]
  [  3   1]
  [  6   9]]

 [[ 41  81]
  [ 31  11]
  [ 61  91]]

 [[  7  71]
  [  5  51]
  [ 13 151]]]


(3, 3, 2)

an array object of arbitary homogenous items 
fast mathematical operations over arrays
linear algebra, fourier transform random number generation

for accessing in array 3 methods
indexing
slicing
subscripting


#array creation functions
np.array()
np.arrange
np.linspace
np.ones
np.zeros
np.eye
np.random.randint()

In [36]:
#indexing
print(m[1][0])
#subscripting
print(m[1,0]) #row,column
print(k[3,1])
print(k[2,0:3:1])  #second row s 0-2 column 1 k step s
print(k[:,1:2])

[41 81]
[41 81]
31
[11 15 17]
[[ 8]
 [ 3]
 [15]
 [31]]


row start ka tk jana h kab tk jana h add hoga vo

In [40]:
print(m[:2,-2:,:1])
print(m[-1:,-2:,:])

[[[ 3]
  [ 6]]

 [[31]
  [61]]]
[[[  5  51]
  [ 13 151]]]
