In [20]:
pip install opencv-python

     ---------------------------------------- 0.0/38.2 MB ? eta -:--:--
     ---------------------------------------- 0.0/38.2 MB 1.4 MB/s eta 0:00:28
     ---------------------------------------- 0.0/38.2 MB 1.4 MB/s eta 0:00:28
     --------------------------------------- 0.0/38.2 MB 330.3 kB/s eta 0:01:56
     --------------------------------------- 0.0/38.2 MB 330.3 kB/s eta 0:01:56
     --------------------------------------- 0.1/38.2 MB 403.5 kB/s eta 0:01:35
     --------------------------------------- 0.1/38.2 MB 469.7 kB/s eta 0:01:22
     --------------------------------------- 0.1/38.2 MB 469.7 kB/s eta 0:01:22
     --------------------------------------- 0.1/38.2 MB 469.7 kB/s eta 0:01:22
     --------------------------------------- 0.1/38.2 MB 469.7 kB/s eta 0:01:22
     --------------------------------------- 0.1/38.2 MB 469.7 kB/s eta 0:01:22
     --------------------------------------- 0.1/38.2 MB 469.7 kB/s eta 0:01:22
     --------------------------------------- 0.2/3


[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
pip install scikit-image

^C
Note: you may need to restart the kernel to use updated packages.


In [22]:
pip install matplotlib

^C
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


     ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.6 MB 330.3 kB/s eta 0:00:23
     ---------------------------------------- 0.0/7.6 MB 330.3 kB/s eta 0:00:23
     ---------------------------------------- 0.0/7.6 MB 330.3 kB/s eta 0:00:23
     ---------------------------------------- 0.0/7.6 MB 131.3 kB/s eta 0:00:58
     ---------------------------------------- 0.0/7.6 MB 131.3 kB/s eta 0:00:58
     ---------------------------------------- 0.1/7.6 MB 172.4 kB/s eta 0:00:44
     ---------------------------------------- 0.1/7.6 MB 208.4 kB/s eta 0:00:37
     ---------------------------------------- 0.1/7.6 MB 209.5 kB/s eta 0:00:36
     ---------------------------------------- 0.1/7.6 MB 209.5 kB/s eta 0:00


[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [12]:
np.arange(1,11,2)
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

range function m floating range nhi skte h 
arrange m d skte h advance version of range

In [7]:
list(range(1,11))
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
np.linspace(1,10,10) #gives 10 evenly spaced no. takes range accordingly

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np.ones([4,5])
np.ones([4,5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
p=np.zeros([4,5])
p

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
p.dtype


dtype('float64')

In [31]:
p.astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
p8=p.astype('uint8')
p8

# 'uint8', 'uint16', 34, 64
# int8, 16,32,64
# float8, 16,32,64

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [47]:
np.random.randint(1,100,5)
np.random.randint(1,100,1)
np.random.randint(1,100,[3,5])   # for random value every time we run

array([[20, 31, 54, 40, 21],
       [54, 64, 51,  9,  2],
       [46, 66, 13, 44, 20]])

In [55]:
# for getting same random value every time we run
# to control randomness
# same seed value when used again gives same array everytime
np.random.seed(30)
np.random.randint(1,100,[3,5])

array([[38, 38, 46, 46, 13],
       [24,  3, 54, 18, 47],
       [ 4, 42,  8, 66, 50]])

In [60]:
np.random.rand(3,4)*1000
np.random.rand(3,4)*100
np.random.rand(3,4)*10000

array([[365.18998439,  47.83089915, 264.1457864 , 463.86716012],
       [693.3550595 , 313.4367534 , 462.53678852, 819.68765269],
       [684.4910251 , 324.03382381, 576.81199915, 632.64998379]])

In [62]:
np.random.randn(3,4) #takes negative no 

array([[-1.27619789, -0.96930035, -0.47545388,  0.14587424],
       [-0.77721569,  0.05740099, -0.70467596,  0.35240827],
       [-1.11441511, -1.1442168 , -0.37604011,  1.28227869]])

In [76]:
# size should be same of each line as it gives back array  
np.loadtxt('data.txt',dtype=str)

array([['this', 'is', 'a', 'new', 'file', 'harshita'],
       ['and', 'we', 'load', 'some', 'data', 'here']], dtype='<U8')

In [85]:
#initially in float data type
np.loadtxt('data1.txt',delimiter=',')

array([[45., 65., 34., 56.],
       [ 2.,  4.,  5.,  6.],
       [ 3., 56., 76.,  2.]])

In [87]:
a=np.random.randint(1,1000,[3,6])
a

array([[ 92,  50, 900, 228, 909, 116],
       [407, 747, 769, 722, 361, 146],
       [ 20, 702, 774, 958, 903, 262]])

In [88]:
np.savetxt('data3.txt',a,delimiter='|',fmt='%d')
# %F for saving in float
# for saving  in laptop

In [90]:
sum(a)
sum(sum(a))

9066

In [96]:
a.sum()

# for sum of the rows
# for statistical values
#rowise axis=1
#columnwise axis=0 
a.sum(axis=1)
a.sum(axis=0)
a.mean(axis=1)  # shows even spacing in between
a.max(axis=1)


array([382.5       , 525.33333333, 603.16666667])

In [99]:
a.argmax(axis=1)
a.argmin(axis=1)
# returning index of that maximum array

array([1, 5, 0], dtype=int64)

In [101]:
a.flatten() #flatten the array

array([ 92,  50, 900, 228, 909, 116, 407, 747, 769, 722, 361, 146,  20,
       702, 774, 958, 903, 262])